/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function genChangelogs(
  repo: string,
  changelogPath?: string | undefined | null
): void;
export function genAllChangelogs(
  repo: string,
  changelogPath?: string | undefined | null
): void;
export function checkPublish(repo: string): void;
