/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol
    [K: symbol]: T
  }
}
export function checkRouters(pathStr: string): boolean
export function genChangelogs(repo: string, changelogPath?: string | undefined | null): void
export function genAllChangelogs(repo: string, changelogPath?: string | undefined | null): void
export function checkPublish(repo: string): void
